# Compare trials and spikes by session

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
import matplotlib.pyplot as plt
import qgrid
#from nma_class import loader
from nma_class_Copy1 import loader

%matplotlib inline

### To compare the trials
Output: 

Table with

session name;	all trials;	correct trials;	diff contrast;	no contrast;	%Correct;	%Contrast;	% 0contrast

In [14]:
# for the first session: 

# link to parent folder with all datasets
main_folder = '/Volumes/GoogleDrive/My Drive/NMA_Dataset/Dataset_1'

from nma_class_Copy1 import loader
#to load older sessions 
loader = loader(main_folder)
all_session_folders, all_session_names = loader.get_available_session()
# load default session 
# put here any integer instead of 0 or directly the folder of the session

session_folder = all_session_folders[0]
session_name =  all_session_names[0]
session = loader.load_session(session_folder, fast=True)

spikes_df = session['spikes_df']
clusters_df = session['clusters_df']
trials_df = session['trials_df']

correct_df = trials_df.loc[(trials_df['feedback type']==1)]
diff_contrasts_df = correct_df.loc[(correct_df['stim contrast left']!=(correct_df['stim contrast right']))]
no_contrasts_df = correct_df.loc[(correct_df['stim contrast left']==0) & (correct_df['stim contrast right']==0)]


all_t = len(trials_df)
crrct = len(correct_df)
cont = len(diff_contrasts_df)
nocont = len(no_contrasts_df)

df1 = ''
df1 = {'session name': [session_name],
      'all trials': [all_t], 
      'correct trials': [crrct], 
      'diff contrast t': [cont], 
      'no contras': [nocont], 
      '%Correct': [round(crrct/all_t*100,2)], 
       '%Contrast':[round(cont/crrct*100,2)], 
       '% 0contrast':[round(nocont/crrct*100,2)]}

df2 = pd.DataFrame(data=df1)


df3 = df2

In [15]:
df3

,session name,all trials,correct trials,diff contrast t,no contras,%Correct,%Contrast,% 0contrast
0,Cori_2016-12-14,214,141,57,84,65.89,40.43,59.57

In [16]:
# link to parent folder with all datasets
main_folder = '/Volumes/GoogleDrive/My Drive/NMA_Dataset/Dataset_1'

from nma_class_Copy1 import loader
#to load older sessions 
loader = loader(main_folder)
all_session_folders, all_session_names = loader.get_available_session()
# load default session 
# put here any integer instead of 0 or directly the folder of the session
for i in range(1,len(all_session_folders)): 
    session_folder = all_session_folders[i]
    session_name =  all_session_names[i]
    session = loader.load_session(session_folder, fast=True)

    spikes_df = session['spikes_df']
    clusters_df = session['clusters_df']
    trials_df = session['trials_df']
    
    correct_df = trials_df.loc[(trials_df['feedback type']==1)]
    diff_contrasts_df = correct_df.loc[(correct_df['stim contrast left']!=(correct_df['stim contrast right']))]
    no_contrasts_df = correct_df.loc[(correct_df['stim contrast left']==0) & (correct_df['stim contrast right']==0)]


    all_t = len(trials_df)
    crrct = len(correct_df)
    cont = len(diff_contrasts_df)
    nocont = len(no_contrasts_df)

    df1 = ''
    df1 = {'session name': [session_name],
          'all trials': [all_t], 
          'correct trials': [crrct], 
          'diff contrast t': [cont], 
          'no contras': [nocont], 
          '%Correct': [round(crrct/all_t*100,2)], 
           '%Contrast':[round(cont/crrct*100,2)], 
           '%0contrast':[round(nocont/crrct*100,2)]}

    df2 = pd.DataFrame(data=df1)
    
    
    df3 = df3.append(df2)

In [17]:
df3

,session name,all trials,correct trials,diff contrast t,no contras,%Correct,%Contrast,% 0contrast
0,Cori_2016-12-14,214,141,57,84,65.89,40.43,59.57
0,Cori_2016-12-17,251,159,57,98,63.35,35.85,61.64
0,Cori_2016-12-18,228,151,55,93,66.23,36.42,61.59
0,Forssmann_2017-11-01,249,166,50,112,66.67,30.12,67.47
0,Forssmann_2017-11-02,254,168,67,94,66.14,39.88,55.95
0,Forssmann_2017-11-04,290,215,81,129,74.14,37.67,60.00
0,Forssmann_2017-11-05,252,169,57,108,67.06,33.73,63.91
0,Hench_2017-06-15,250,161,85,73,64.40,52.80,45.34
0,Hench_2017-06-16,372,255,108,146,68.55,42.35,57.25
0,Hench_2017-06-17,447,277,123,150,61.97,44.40,54.15
0,Hench_2017-06-18,342,272,101,166,79.53,37.13,61.03
0,Lederberg_2017-12-05,340,251,100,146,73.82,39.84,58.17
0,Lederberg_2017-12-06,300,239,100,135,79.67,41.84,56.49
0,Lederberg_2017-12-07,268,186,72,111,69.40,38.71,59.68
0,Lederberg_2017-12-08,404,309,138,167,76.49,44.66,54.05
0,Lederberg_2017-12-09,280,201,82,118,71.79,40.80,58.71
0,Lederberg_2017-12-10,224,186,85,99,83.04,45.70,53.23
0,Lederberg_2017-12-11,316,247,101,144,78.16,40.89,58.30
0,Moniz_2017-05-15,247,142,61,76,57.49,42.96,53.52
0,Moniz_2017-05-16,235,139,49,82,59.15,35.25,58.99
0,Moniz_2017-05-18,124,66,27,39,53.23,40.91,59.09
0,Muller_2017-01-07,444,311,115,187,70.05,36.98,60.13
0,Muller_2017-01-08,151,102,43,58,67.55,42.16,56.86
0,Muller_2017-01-09,187,109,47,60,58.29,43.12,55.05
0,Radnitz_2017-01-08,261,188,75,108,72.03,39.89,57.45
0,Radnitz_2017-01-09,178,130,60,69,73.03,46.15,53.08
0,Radnitz_2017-01-10,253,159,68,89,62.85,42.77,55.97
0,Radnitz_2017-01-11,142,85,42,42,59.86,49.41,49.41
0,Radnitz_2017-01-12,128,75,31,42,58.59,41.33,56.00
0,Richards_2017-10-29,143,72,26,46,50.35,36.11,63.89
0,Richards_2017-10-30,237,164,73,89,69.20,44.51,54.27
0,Richards_2017-10-31,260,186,96,88,71.54,51.61,47.31
0,Richards_2017-11-01,191,129,62,66,67.54,48.06,51.16
0,Richards_2017-11-02,296,176,90,85,59.46,51.14,48.30
0,Tatum_2017-12-06,311,240,98,140,77.17,40.83,58.33
0,Tatum_2017-12-07,258,188,87,98,72.87,46.28,52.13
0,Tatum_2017-12-08,181,132,64,65,72.93,48.48,49.24
0,Tatum_2017-12-09,199,131,56,73,65.83,42.75,55.73
0,Theiler_2017-10-11,343,246,78,168,71.72,31.71,68.29

In [18]:
#to save
#df3.to_csv (r'/Users/kcenia/Documents/GitHub/NMA_project/kce/trials_comparison_df.csv', index = False, header=True)

In [12]:
#test
A = [1, 2, 3,4,5,6,7]
for i in range(3,len(A)):
    print(i, A[i])

3 4
4 5
5 6
6 7

### To plot the trials